services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3333:3333
    volumes:
      - node_modules:/usr/src/app/node_modules
    develop:
      watch:
        - action: sync
          path: ./src
          target: /usr/src/app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

volumes:
  node_modules: {}
