POST http://localhost:3333/tasks
Content-Type: application/json

# Body
{
    "title": "Task 1",
    "description": "Essa é a task 01",
    "is_checked": false
}

###


GET http://localhost:3333/tasks


###

GET http://localhost:3333/tasks?search=edtiada

###

PUT http://localhost:3333/tasks/7dc6e124-6627-4fc9-bc8d-dca22fe7bdf4
Content-Type: application/json

# Body
{
    "title": "Task edtiada",
    "description": "Essa é uma task que foi editada",
    "is_checked": false
}

###

DELETE  http://localhost:3333/tasks/888587bf-a600-490b-9677-2bda3e6cb26e